<?php

namespace AppBundle\Repository;

/**
 * PresenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresenterRepository extends \Doctrine\ORM\EntityRepository
{
}
