app:
    resource: "@AppBundle/Controller/"
    type:     annotation
app_schedule:
    resource: "@AppBundle/Controller/ScheduleController.php"
    type: rest
app_presenter:
    resource: "@AppBundle/Controller/PresenterController.php"
    type: rest