# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    schedule_repository:
        class: AppBundle\Repository\ScheduleRepository
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['AppBundle:Schedule']

    presenter_repository:
        class: AppBundle\Repository\PresenterRepository
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['AppBundle:Presenter']

    app.slack_outgoing_webhook.action_listener:
        class: AppBundle\EventListener\SlackWebhookTokenListener
        arguments: ['%out_going_webhook_tokens%']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
